#############################################################################
# Makefile for building: ImageShackUploader.app/Contents/MacOS/ImageShackUploader
# Generated by qmake (2.01a) (Qt 4.8.0) on: Fri Mar 9 00:24:38 2012
# Project:  ImageShackUploader.pro
# Template: app
# Command: /Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -o Makefile ImageShackUploader.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/default -I. -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtNetwork.framework/Versions/4/Headers -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtNetwork -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtXml.framework/Versions/4/Headers -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtXml -I../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/include -I. -I. -F/Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/lib -framework QtXml -framework QtGui -framework QtNetwork -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ImageShackUploader.cpp \
		main.cpp \
		Window.cpp \
		ImageShackResponse.cpp \
		ImageShackObject.cpp \
		ImageShackError.cpp moc_ImageShackUploader.cpp \
		moc_Window.cpp \
		moc_ImageShackResponse.cpp \
		moc_ImageShackObject.cpp \
		moc_ImageShackError.cpp
OBJECTS       = ImageShackUploader.o \
		main.o \
		Window.o \
		ImageShackResponse.o \
		ImageShackObject.o \
		ImageShackError.o \
		moc_ImageShackUploader.o \
		moc_Window.o \
		moc_ImageShackResponse.o \
		moc_ImageShackObject.o \
		moc_ImageShackError.o
DIST          = ../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		ImageShackUploader.pro
QMAKE_TARGET  = ImageShackUploader
DESTDIR       = 
TARGET        = ImageShackUploader.app/Contents/MacOS/ImageShackUploader

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile ImageShackUploader.app/Contents/PkgInfo ImageShackUploader.app/Contents/Resources/empty.lproj ImageShackUploader.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ImageShackUploader.app/Contents/MacOS/ || $(MKDIR) ImageShackUploader.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ImageShackUploader.pro  ../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/default/qmake.conf ../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile ImageShackUploader.pro
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile ImageShackUploader.pro

ImageShackUploader.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) ImageShackUploader.app/Contents || $(MKDIR) ImageShackUploader.app/Contents 
	@$(DEL_FILE) ImageShackUploader.app/Contents/PkgInfo
	@echo "APPL????" >ImageShackUploader.app/Contents/PkgInfo
ImageShackUploader.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) ImageShackUploader.app/Contents/Resources || $(MKDIR) ImageShackUploader.app/Contents/Resources 
	@touch ImageShackUploader.app/Contents/Resources/empty.lproj
	
ImageShackUploader.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) ImageShackUploader.app/Contents || $(MKDIR) ImageShackUploader.app/Contents 
	@$(DEL_FILE) ImageShackUploader.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,ImageShackUploader,g" -e "s,@TYPEINFO@,????,g" ../../../System/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/default/Info.plist.app >ImageShackUploader.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/ImageShackUploader1.0.0 || $(MKDIR) .tmp/ImageShackUploader1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ImageShackUploader1.0.0/ && $(COPY_FILE) --parents ImageShackUploader.hpp Window.hpp ImageShackResponse.hpp ImageShackObject.hpp ImageShackError.hpp .tmp/ImageShackUploader1.0.0/ && $(COPY_FILE) --parents ImageShackUploader.cpp main.cpp Window.cpp ImageShackResponse.cpp ImageShackObject.cpp ImageShackError.cpp .tmp/ImageShackUploader1.0.0/ && (cd `dirname .tmp/ImageShackUploader1.0.0` && $(TAR) ImageShackUploader1.0.0.tar ImageShackUploader1.0.0 && $(COMPRESS) ImageShackUploader1.0.0.tar) && $(MOVE) `dirname .tmp/ImageShackUploader1.0.0`/ImageShackUploader1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ImageShackUploader1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r ImageShackUploader.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_ImageShackUploader.cpp moc_Window.cpp moc_ImageShackResponse.cpp moc_ImageShackObject.cpp moc_ImageShackError.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ImageShackUploader.cpp moc_Window.cpp moc_ImageShackResponse.cpp moc_ImageShackObject.cpp moc_ImageShackError.cpp
moc_ImageShackUploader.cpp: ImageShackError.hpp \
		ImageShackObject.hpp \
		ImageShackResponse.hpp \
		ImageShackUploader.hpp
	/Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ImageShackUploader.hpp -o moc_ImageShackUploader.cpp

moc_Window.cpp: ImageShackObject.hpp \
		ImageShackUploader.hpp \
		ImageShackError.hpp \
		ImageShackResponse.hpp \
		Window.hpp
	/Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Window.hpp -o moc_Window.cpp

moc_ImageShackResponse.cpp: ImageShackObject.hpp \
		ImageShackResponse.hpp
	/Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ImageShackResponse.hpp -o moc_ImageShackResponse.cpp

moc_ImageShackObject.cpp: ImageShackObject.hpp
	/Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ImageShackObject.hpp -o moc_ImageShackObject.cpp

moc_ImageShackError.cpp: ImageShackError.hpp
	/Users/supm4n/System/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ImageShackError.hpp -o moc_ImageShackError.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

ImageShackUploader.o: ImageShackUploader.cpp ImageShackUploader.hpp \
		ImageShackError.hpp \
		ImageShackObject.hpp \
		ImageShackResponse.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageShackUploader.o ImageShackUploader.cpp

main.o: main.cpp Window.hpp \
		ImageShackObject.hpp \
		ImageShackUploader.hpp \
		ImageShackError.hpp \
		ImageShackResponse.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Window.o: Window.cpp Window.hpp \
		ImageShackObject.hpp \
		ImageShackUploader.hpp \
		ImageShackError.hpp \
		ImageShackResponse.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o Window.cpp

ImageShackResponse.o: ImageShackResponse.cpp ImageShackResponse.hpp \
		ImageShackObject.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageShackResponse.o ImageShackResponse.cpp

ImageShackObject.o: ImageShackObject.cpp ImageShackObject.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageShackObject.o ImageShackObject.cpp

ImageShackError.o: ImageShackError.cpp ImageShackError.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageShackError.o ImageShackError.cpp

moc_ImageShackUploader.o: moc_ImageShackUploader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageShackUploader.o moc_ImageShackUploader.cpp

moc_Window.o: moc_Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Window.o moc_Window.cpp

moc_ImageShackResponse.o: moc_ImageShackResponse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageShackResponse.o moc_ImageShackResponse.cpp

moc_ImageShackObject.o: moc_ImageShackObject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageShackObject.o moc_ImageShackObject.cpp

moc_ImageShackError.o: moc_ImageShackError.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageShackError.o moc_ImageShackError.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

